name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your cooperation 😊✨; we will address this matter as quickly as possible! 🚀💪"
        pr-message: "We appreciate your participation! Rest assured, we will combine your pull request as quickly as a cat snatching a cup of coffee."
